sudo: required
language: go
go_import_path: github.com/open-policy-agent/opa-envoy-plugin
go:
- '1.15'
services:
- docker
env:
  global:
jobs:
  include:
    - stage: "build, test, deploy"
      script: make
      deploy:
        - provider: script
          skip_cleanup: true
          script: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && make deploy-travis
          on:
            repo: open-policy-agent/opa-envoy-plugin
            branch: master
            tags: false
    - stage: e2e
      if: (NOT type IN (pull_request)) AND (branch = master)
      before_script:
      - KIND_VERSION=0.4.0
      - ISTIO_VERSION=1.5.0
      # Download and install kind
      - curl -L https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64 --output kind && chmod +x kind && sudo mv kind /usr/local/bin/
      # Create kind cluster
      - |
        if [ $(kind get clusters) ]; then
          export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
        else
          kind create cluster
        fi
      # Get kubeconfig
      - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
      # Download and install kubectl
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv kubectl /usr/local/bin/
      # Download and install Istio
      - curl -L https://git.io/getLatestIstio | ISTIO_VERSION=${ISTIO_VERSION} sh - && mv istio-${ISTIO_VERSION} /tmp && cd /tmp/istio-${ISTIO_VERSION} && for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done && kubectl apply -f install/kubernetes/istio-demo.yaml && cd -
      - kubectl -n istio-system wait --for=condition=available --timeout=600s --all deployment
      script:
      - make update-istio-quickstart-version && make test-e2e
      after_script:
      - kind delete cluster
