name: proxy_init Tag

on:
  push:
    branches:
      - main
    tags:
      - 'proxy_init-v*'

jobs:
  deploy:
    name: Build and deploy proxy_init container
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set TAG_NAME in Environment
        # Subsequent jobs will be have the computed tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Workaround Buildx Errors
        run: build/buildx_workaround.sh

      - name: Login to Docker
        run: make docker-login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push proxy_init
        run: make VERSION=v${TAG_NAME#*v} -C proxy_init push
